#!/bin/bash

cd /home/lsminer/lsminer

function usage()
{
	printf "console\n\n"
	printf "Usage: console [OPTION]\n\n"
	printf "start: Start console Service\n"
	printf "stop: Stop console Service\n"
	printf "restart: Restart console Service\n"

}

function start()
{

	SCREEN=$(screen -ls console | grep console | wc -l)
	[ "$SCREEN" -gt 1 ] && echo "console service already running..." && exit

	echo "console Starting..."

	if [ -f "/home/lsminer/screen_console.log" ]; then
	 	sudo rm -rf /home/lsminer/screen_console.log
	fi

	if [ -f "/home/lsminer/teleconsole.id" ]; then
	 	sudo rm -rf /home/lsminer/teleconsole.id
	fi

	screen -dm -S console -t console -L bash -c "/home/lsminer/lsminer/teleconsole"

	while true; do
		sleep 2
		TELELOG=$(cat /home/lsminer/screen_console.log | grep -m1 "WebUI for this session: ")

		if [[ ! -z $TELELOG ]]; then
			
			TELELOG=$(sed "s,$(printf '\033')\\[[0-9;]*[a-zA-Z],,g" <<< "$TELELOG")
			TELECONSOLE_ID=$(awk '{print $NF}' <<< "$TELELOG")

			if [[ ! -z $TELECONSOLE_ID ]]; then
				echo "Teleconsole ID generated: $TELECONSOLE_ID"
				echo $TELECONSOLE_ID | tee /home/lsminer/teleconsole.id
				wait && sync && sleep 1
				TELEID=$(cat /home/lsminer/teleconsole.id | grep -m1 "http")
				if [[ ! -z $TELEID ]]; then
					echo "Write!"
					break
				fi
			fi
			
		fi
	done

}


function stop()
{
	screens=`screen -ls console | grep -E "[0-9]+\.console" | cut -d. -f1 | awk '{print $1}'`

	if [[ -z $screens ]]; then
		echo "No console screens found"
	else
		for pid in $screens; do
			echo "Stopping screen session: $pid.console"
			screen -S $pid -X quit
		done
	fi

	sudo rm -rf /home/lsminer/screen_console.log
	sudo rm -rf /home/lsminer/teleconsole.id
}



case $1 in
	start)
		start
	;;
	stop)
		stop
	;;
	restart)

		echo "Restarting console"
		stop
		wait && sync && sleep 1
		start
	;;
	*)
		usage
	;;
esac