#!/bin/bash
cd /home/lsminer/lsminer

function text()
{
	local color=${1}
	shift
	local text="${@}"
	case ${color} in
    	red    ) tput setaf 1 ; tput bold ;;
    	green  ) tput setaf 2 ; tput bold ;;
    	yellow ) tput setaf 3 ; tput bold ;;
    	blue   ) tput setaf 4 ; tput bold ;;
    	purple ) tput setaf 5 ; tput bold ;;
		cyan   ) tput setaf 6 ; tput bold ;;
		white  ) tput setaf 7 ; tput bold ;;
	esac
	echo -en "${text}"
	tput sgr0
}

function intro()
{
	LOGO=$(cat /home/lsminer/lsminer/logo)
	DARKGRAY='\033[1;30m'
	RESETCOLOR='\033[0m'

	echo -e "${DARKGRAY}------------------------------------------------------------------------------${RESETCOLOR}\n\n"
	echo "\n\n"
	text cyan "$LOGO\n"
	text cyan "		     Linux Mining Operating System\n\n\n"

	echo -e "${DARKGRAY}------------------------------------------------------------------------------${RESETCOLOR}\n\n"
}

intro

text cyan "The miner is starting\n\n"

export CUDA_DEVICE_ORDER=PCI_BUS_ID
export DISPLAY=:0
export GPU_MAX_ALLOC_PERCENT=100
export GPU_MAX_HEAP_SIZE=100
export GPU_SINGLE_ALLOC_PERCENT=100
export GPU_USE_SYNC_OBJECTS=1
export GPU_FORCE_64BIT_PTR=1 # CAUTION !!
export LD_LIBRARY_PATH=/home/lsminer/lsminer/libcuda

#检查accesskey文件是否正常，如果为空，用户必须手动输入accesskey
ACCESSKEY=$(cat /home/lsminer.conf | cut -d ' ' -f 1 | tr '[:upper:]' '[:lower:]' | tr -d '\r' | tr -d '\n')

if [ -z "$ACCESSKEY" ]; then

	CURRENT_ACCESSKEY=$(cat /home/lsminer.conf | cut -d ' ' -f 1 | tr '[:upper:]' '[:lower:]' | tr -d '\r' | tr -d '\n')
	echo $CURRENT_ACCESSKEY
	NEW_ACCESSKEY=''
	while [ -z "$NEW_ACCESSKEY"]; do
		NEW_ACCESSKEY=$(DISPLAY=:0 sudo zenity --entry --text="\n\n你必须设置Accesskey使设备和账号进行绑定，登陆后台可以查看Accesskey，或者联系客服。\n"  --title="更改Accesskey" --width=600 --height=220 --entry-text="$CURRENT_ACCESSKEY")
		wait && sleep 1
	done
	
	echo "$NEW_ACCESSKEY" | sudo tee /home/lsminer.conf > /dev/null 2>&1
	DISPLAY=:0 sudo zenity --info --text="\n<b>Accesskey已经成功修改</b>" --ellipsize 

fi

wait && sync && sleep 1

python3 /home/lsminer/lsminer/update.py

